DROP TABLE IF EXISTS TBL_CARRIER_COMPANY;

CREATE TABLE TBL_CARRIER_COMPANY (
  carrier_id INT AUTO_INCREMENT  PRIMARY KEY,
  carrier_name VARCHAR(250) NOT NULL,
  carrier_code VARCHAR(10) NOT NULL
);
